import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import { MangosContextProvider } from "@/shared/context";
import { Toaster } from "@/shared/components/ui/toaster";
import { Header } from "@/widgets/Header/Header";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<MangosContextProvider>
					<Header />
					<main>{children}</main>
				</MangosContextProvider>
				<Toaster />
			</body>
		</html>
	);
}
