enum EndpointKeys {
    login = 'login',
    register = 'register',
    refresh = 'refresh',
    logout = 'logout',
    me ='me',
    activity_types = 'activity_types',
    categories = 'categories',
    divisions = 'divisions',
    execution_statuses = 'execution_statuses',
    notifications = 'notifications',
    organizations = 'organizations',
    organization_employees = 'organization_employees',
    posts = 'posts',
    projects = 'projects',
    project_members = 'project_members',
    roles = 'roles',
    tags = 'tags',
    tasks = 'tasks',
    task_members = 'task_members',
    task_priorities = 'task_priorities',
    task_tags = 'task_tags',
    users = 'users',
};

export const endpoints: Record<EndpointKeys, string> = {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    activity_types: '/activity_types',
    categories: '/categories',
    divisions: '/divisions',
    execution_statuses: '/execution_statuses',
    notifications: '/notifications',
    organizations: '/organizations',
    organization_employees: '/organization_employees',
    posts: '/posts',
    projects: '/projects',
    project_members: '/project_members',
    roles: '/roles',
    tags: '/tags',
    tasks: '/tasks',
    task_members: '/task_members',
    task_priorities: '/task_priorities',
    task_tags: '/task_tags',
    users: '/users',
}